name: cool

on: [push]

jobs:
    ubuntu:
        name: running action on ubuntu
        runs-on: ubuntu-latest
        steps:
          - name: Step one
            uses: actions/upload-artifact@v1.0.0

          - name: Step Two
            run: echo "Hello world!" && date

          - name: Step Three
            uses: actions/upload-artifact@v1.0.0

    windows:
        name: running action on windows
        runs-on: windows-latest
        needs: [ubuntu]
        steps:
          - name: Step one
            uses: actions/download-artifact@v1.0.0

          - name: Step Two
            run: echo "Hello world!" && date

          - name: Step Three
            uses: actions/download-artifact@v1.0.0

